### ISSUE TITLE
Lightbox Not Working

### ISSUE THREAD

**Issue by fewlo** [archetyped/slb-addons#16]
Hi,

I can't get the Video Lightbox to work, here is the problem test page:

http://www.ads-designs.com/vid-test/

I've cleared my cache and also tried in both Firefox and IE.

Also, does the plugin work with videos in a sidebar?

Many thanks, Michael,

**Comment by archetyped** [comment]
Hi, SLB works with links, but the link you provided does not have any links, just embedded players.  Adding a link to a supported video (e.g. YouTube or Vimeo video URL) to your post should allow SLB to display the video in the lightbox.

The video add-on works everywhere SLB does.  If you have SLB enabled for widgets, then supported links in your sidebar widgets should also be displayed in the lightbox.
