### ISSUE TITLE
[Video / Issue]: Video opens in full screen at Vimeo

### ISSUE THREAD

**Issue by greggluhring** [archetyped/slb-addons#17]
## Description of issue
Using slb video add-on when a single image is clicked, instead of playing in a lightbox the viewer is taken to vimeo
Image is on the right halfway down the page "Dick and Jane are here"

I know this is probably something simple. I'm just fried out on this site. Just want it to be done with. Sorry.

## Details

* URL of page exhibiting the issue: http://lsrproof.info/
* Web Browser(s) that exhibit the issue: Firefox 36 Mac
* Simple Lightbox Version: SLB 2.3.1
* Active theme: Child of Nimva
* Other plugins installed: 
Admin Menu Tree Page View
Version 2.6.9 | By Pär Thernström |

BackupBuddy
Version 5.2.0.0 | By iThemes |

Child Theme Configurator
Version 1.7.1 | By Lilaea Media |

Contact Form 7
Version 4.1 | By Takayuki Miyoshi |

Duplicate Post
Version 2.6 | By Enrico Battocchi

LayerSlider WP
Version 5.3.2 | By Kreatura Media

Post Types Order
Version 1.7.7

Simple Lightbox
Version 2.3.1 | By Archetyped

Simple Lightbox: Video Handler
Version 0.1.0 | By Archetyped |

Spots
Version 1.3.3 | By Robert O'Rourke

TinyMCE Advanced
Version 4.1.7 | By Andrew Ozz |

WordPress Zero Spam
Version 1.5.3 | By Ben Marshall

WP Admin UI Customize
Version 1.5.2.6 | By gqevu6bsiz |

WPsite Show IDs
Version 1.0.3

**Comment by archetyped** [comment]
Hi, the video add-on currently supports direct video URIs.  For example, the thumbnail on your page links to `https://vimeo.com/user3700087/dickandjanelikefandf`, but the actual URI that is loaded is `https://vimeo.com/121400024`.

Changing the link on the page to the direct video URI (`https://vimeo.com/121400024`) should allow SLB to activate the link.
