### ISSUE TITLE
[Video / Request]: Related Videos at the end of the video - Youtube

### ISSUE THREAD

**Issue by nkovo5983** [archetyped/slb-addons#21]
## Description of feature/request

Option added to not show related videos at the end of the youtube video. 

We are adding our videos to our new website utilizing this plugin add-on but when we try to add the youtube link with the rel=0 or any combination to not show any related videos when its done playing, it just shows the loading icon.

An example of a raw youtube video is here: "https://www.youtube.com/watch?v=wXQUhX89vtQ" which works but when its complete it shows related videos that may or may not pertain to our company.

what i am trying to do is something like this: "https://www.youtube.com/watch?v=wXQUhX89vtQ?rel=0" please note the "?rel=0" at the end. The plugin needs to be updated to either allow the option to remove the related videos at the end or supply the code to allow the rel=0.

There is a plugin called "Hide Youtube Related Videos" by SparkWeb Interactive, Inc. that does just that, removes the related videos, but for some reason it doesnt work inside your light box.

Please Help!?!?

## This feature would be used to

Not display competitor videos at the end of our corporate videos or any video that is obscene or not user friendly.

**Comment by archetyped** [comment]
Hi, thanks for the feedback! Support for query variables is planned for an upcoming update.

**Comment by bradydan** [comment]
I second this feature request

**Comment by archetyped** [comment]
Hi, this enhancement is currently in progress.  Please refer to the [existing ticket](4) for further details and updates.
