### ISSUE TITLE
Video lightbox not working on IIS

### ISSUE THREAD

**Issue by bradydan** [archetyped/slb-addons#23]
Reach the home page by clicking 'skip' or the logo on this page http://wp-dev.gavurin.com/ 

The video lightbox is under the ''Take a quick tour" header, click on the video screengrab

Same site on a linux server, works fine: http://gavurin.consil.co.uk/

Installed: 
* Simple Lightbox  2.4.0
* Display videos with Simple Lightbox 0.1.0 

Any ideas?

**Comment by bradydan** [comment]
FYI cURL is installed

**Comment by bradydan** [comment]
PHP is v 5.6

**Comment by archetyped** [comment]
Hi, clicking either of those links reloads the splash page.  Please provide a direct link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by bradydan** [comment]
Sorry, fixed now. Please try again.

**Comment by bradydan** [comment]
Do you have a list of server requirements for the plugin and add-on?

**Comment by archetyped** [comment]
Hi, here are [SLB's minimum requirements](../wiki/Requirements).

If you have confirmed that cURL is enabled, you may also need to check to make sure that cURL is enabled for PHP, and that it is enabled for local requests.

**Comment by bradydan** [comment]
I can't access that page in the wiki. The only pages I can see in the wiki are 'Home' and 'Report an issue'.

Can you please post the requirements here? 

thanks

**Comment by bradydan** [comment]
Or did you mean to link to this page?

https://github.com/archetyped/simple-lightbox/wiki/Requirements

**Comment by bradydan** [comment]
As far as I can tell we are meeting the requirements. There's a PHPinfo page here  http://wp-dev.gavurin.com/index2.php

Any ideas why the lightbox isn't working?

__HTML output on live server (IIS)__ http://wp-dev.gavurin.com/ :

```
<a class="act" data-slb-active="1" href="https://www.youtube.com/watch?v=zasJ2Z7WpRo">
<img class="aligncenter size-full wp-image-336" width="510" height="287" data-slb-group="1416" data-slb-active="1" alt="gavurin-video-bg" src="http://wp-dev.gavurin.com/wp-content/uploads/2015/03/gavurin-video-bg.jpg">
</a>
```

__HTML output on dev server (Linux)__ http://gavurin.consil.co.uk/

```
<a class="act" data-slb-active="1" href="https://www.youtube.com/watch?v=zasJ2Z7WpRo">
<img class="aligncenter size-full wp-image-336" width="510" height="287" data-slb-group="1416" data-slb-active="1" alt="gavurin-video-bg" src="http://gavurin.consil.co.uk/wp-content/uploads/2015/03/gavurin-video-bg.jpg">
</a>
```

So, apart from the src URL, the HTML is identical. Which I interpret as the shortcode working. But the implementation is not.

Both live and dev home pages are delivering 44 JS files

Any ideas?

**Comment by archetyped** [comment]
It appears that cURL may not be enabled for local requests, which prevents WordPress from being able to load some of SLB's resources (such as the lightbox's layout).

This is a setting at the server level, not within PHP.  I would recommend contacting your host to check if they have disabled/blocked local cURL requests.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
