### ISSUE TITLE
[Video / Request]: 

### ISSUE THREAD

**Issue by in2gether** [archetyped/slb-addons#24]
## Description of feature/request
Could you please integrate support / option for loading locally stored videos to open in the lightbox?
And if possible - from Amazon S3 account

## This feature would be used to
I have some videos stored locally on my server, with custom overlay and links embedded, as well as videos stores on Amazon S3. Would be great to use these inside the lightbox.

**Comment by archetyped** [comment]
Hi, please add the specific file types you would like supported in the [File Support thread](25).

Thanks.
