### ISSUE TITLE
[WooCommerce / Issue]: CSS Customization

### ISSUE THREAD

**Issue by mattangel** [archetyped/slb-addons#26]
## Identifying CSS for Simple Lightbox

I would like to style Simple Lightbox and remove title from WP media showing in slideshow. I cannot find corresponding CSS to resolve this. Any help would be appreciated.

* URL of page exhibiting the issue: http://solbonita.mattangel.com.au/product/jardinera/
* Web Browser(s) that exhibit the issue: all
* Simple Lightbox Version: 2.4.1
* Active theme: Divi
* Other plugins installed: Simple Lightbox Woocommerce Activator

**Comment by archetyped** [comment]
Hi, here's a [tutorial on customizing SLB theme styles](http://archetyped.com/know/slb-theme-styles/).

Creating a custom theme is recommended ([tutorial](http://archetyped.com/know/slb-theme-anatomy/)), as modifications to SLB's default themes will be overwritten by any update to SLB.
