### ISSUE TITLE
[Video / Issue]: Lightbox player does not play

### ISSUE THREAD

**Issue by CareyBryson** [archetyped/slb-addons#27]
Simple Lightbox and Simple Lightbox video are installed on the site. 

When we click on the link to our YouTube video, the screen goes dark like the video is about to play, but nothing happens.

* URL of page exhibiting the issue: http://apstraining.com/uprt-programs/
*Youtube video is the link with the following text: Short Video on How to Use this Page.
* Web Browser(s) that exhibit the issue: all
* Simple Lightbox Version: 2.4.1

**Comment by archetyped** [comment]
Hi, your site appears to be loading an outdated version of jQuery.  SLB requires the version of jQuery officially included with WordPress to function properly.

See here for more information: [jQuery Support](../wiki/jQuery-Support).

Removing the outdated version of jQuery and allowing WordPress to load the officially supported version should allow SLB to function properly.  Please update this ticket if you are still experiencing a problem after you have resolved this issue and I would be glad to reopen the ticket and take another look.

Thanks.

**Comment by apstraining** [comment]
The issue remains. 

For reference for the plugin developer, I get the following console errors:
XHR finished loading: GET "http://apstraining.com/wp-admin/admin-ajax.php?action=slb_video_data&provider=youtube.com&src_uri=https%3A%2F%2Fyoutu.be%2Fcb16nvQHzHM".send @ jquery.min.js:2v.extend.ajax @ jquery.min.js:2v.(anonymous function) @ jquery.min.js:2v.extend.getJSON @ jquery.min.js:2SLB.View.extend_content_handler.load @ handler.video.js?ver=2.4.1:22Component.call_attribute @ lib.view.js?ver=2.4.1:1Content_Handler.load @ lib.view.js?ver=2.4.1:1Content_Item.load @ lib.view.js?ver=2.4.1:2Content_Item.show @ lib.view.js?ver=2.4.1:2View.show_item @ lib.view.js?ver=2.4.1:1handler @ lib.view.js?ver=2.4.1:1v.event.dispatch @ jquery.min.js:2o.handle.u @ jquery.min.js:2
 
www-embed-player-new.js:112 GET chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js net::ERR_FAILEDAh @ www-embed-player-new.js:112zh @ www-embed-player-new.js:112yh @ www-embed-player-new.js:112Bh @ www-embed-player-new.js:113Hj @ www-embed-player-new.js:173Sm @ www-embed-player-new.js:268zp @ www-embed-player-new.js:310(anonymous function) @ cb16nvQHzHM?feature=oembed&wmode=transparent:10
 
www-embed-player-new.js:112 GET chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js net::ERR_FAILEDAh @ www-embed-player-new.js:112zh @ www-embed-player-new.js:112(anonymous function) @ www-embed-player-new.js:112c.onerror @ www-embed-player-new.js:112
 
www-embed-player-new.js:112 GET chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js net::ERR_FAILEDAh @ www-embed-player-new.js:112zh @ www-embed-player-new.js:112(anonymous function) @ www-embed-player-new.js:112c.onerror @ www-embed-player-new.js:112
 
www-embed-player-new.js:112 GET chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js net::ERR_FAILEDAh @ www-embed-player-new.js:112zh @ www-embed-player-new.js:112(anonymous function) @ www-embed-player-new.js:112c.onerror @ www-embed-player-new.js:112
 
www-embed-player-new.js:112 GET chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js net::ERR_FAILEDAh @ www-embed-player-new.js:112zh @ www-embed-player-new.js:112(anonymous function) @ www-embed-player-new.js:112c.onerror @ www-embed-player-new.js:112
 
www-embed-player-new.js:112 GET chrome-extension://eojlgccfgnjlphjnlopmadngcgmmdgpk/cast_sender.js net::ERR_FAILED

**Comment by archetyped** [comment]
Hi, your site is still loading an outdated version of jQuery.  SLB is not able to function properly until the outdated version of jQuery is removed.  Here are some [instructions on determining what plugin/theme is loading the outdated version of jQuery](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts) if you are not sure how it is being loaded.

Regarding the console messages, the only one related to SLB appears to simply be informational, not an error.  The other messages are errors, but appears to be related to browser extensions you have installed.

**Comment by apstraining** [comment]
Ok - can we use your Archtyped Concierge service to get this fixed? We have a major branding announcement going out today and would like this functionality. We installed a plug-in called jQuery Updater last night that appeared to solve the jQuery issue but that was well before the message you posted above.

**Comment by archetyped** [comment]
Hi, SLB appears to now be working at the link you provided.  If you are still experiencing this issue, clearing your browser's cache is recommended.

Also, note that using an additional plugin to load a different version of jQuery than is officially supported by WordPress is not recommended.  Unexpected behavior with WordPress, SLB, and other plugins that use the version of jQuery that is included with WordPress may occur as a result.  The recommended solution is to disable the plugin/theme that is loading the outdated version of jQuery to allow WordPress to load its own version.
