### ISSUE TITLE
[Video / Issue]: Not working on site after activating plugin

### ISSUE THREAD

**Issue by lizcdesign** [archetyped/slb-addons#30]
Hello,

I recently uploaded the plugin and activated it, but it isn't opening the Youtube video in the fancybox.

In Chrome, it goes straight to youtube to play. In Firefox, it acts like it is going to open in a fancy box but then it opens in Youtube. 

I have both plugins(simple and video) active, please let me know if I missed a step.

I am testing this plugin on this draft/page:  https://www.ecomdash.com/compare-page-mock-up/ 

The bottom button: Get Started Now! and the button that says See how it works(screenshot below) are both linking to the youtube video. I cleared my cache multiple times. Please note that the See How it Works buttons does exist in a Revolution slider. 

![image](https://cloud.githubusercontent.com/assets/14352205/9968379/162f3052-5e16-11e5-8097-028ef0d49e08.png)

Please let me know if you need more information.

Thanks,
Liz

* URL of page exhibiting the issue: https://www.ecomdash.com/compare-page-mock-up/ 
* Web Browser(s) that exhibit the issue: Chrome/Firefox
* Simple Lightbox Version: Version 2.5.1
* Active theme: X
* Other plugins installed: Akismet, BAW Manual related Posts, Column Shortcodes, EWWW Image Optimizer Cloud, Force Regenerate Thumbnails, Gravity Forms, Image Mouseover, KISSmetrics, LeadDyno Wordpress Plugin, Locatoraid, Mialchimp, Master Slider, Rev Slider, Simple Share Buttons, Testimonial Slider, velvet Blues Update URLs, WPBakery Visual Composer, WPide, X Shortcodes, Yoast SEO

**Comment by archetyped** [comment]
Hi, it looks like your site may be blocking AJAX requests to `/wp-admin/admin-ajax.php`.  You may have to contact your hosting provider to configure the site to unblock such requests.

Once AJAX requests are enabled, SLB and the video add-on should be able to function normally.

If you are still experiencing a problem after AJAX requests have been enabled, please let me know what you find and I would be glad to take another look.

**Comment by lizcdesign** [comment]
Thank you for your response. I will work with WPEngine on this.

I will reach out if they have any questions.

Thanks,
Liz


Liz Pekarek
Marketing
704.687.8067 o | 910.734.8876 c
eCommerce, Automated.

ecomdash.com<http://www.ecomdash.com/>

**Comment by lizcdesign** [comment]
Hello,

My web host, WPEngine, came up with a hack – by adding target=”_blank” – it forces the browser to open in the lightbox. I tested it for both Chrome and Firefox and it works!

Thanks,
Liz


Liz Pekarek
Marketing
704.687.8067 o | 910.734.8876 c
eCommerce, Automated.

ecomdash.com<http://www.ecomdash.com/>

**Comment by archetyped** [comment]
It's strange that the `target` attribute makes a difference, but I'm glad you were able to find a solution.
