### ISSUE TITLE
[WooCommerce Add On] It's not working

### ISSUE THREAD

**Issue by phases-design** [archetyped/slb-addons#31]
## Description of issue

Are their settings or something that I need to be looking for? (couldn't find any) 
I have Woocommerce installed, Simple Lightbox, Simple Lightbox: WooCommerce Activator...all current versions. 

So, where oh where are my lightboxes?

## Details

* URL of page exhibiting the issue: 
* Web Browser(s) that exhibit the issue: 
* Simple Lightbox Version: 
* Active theme: 
* Other plugins installed:

**Comment by phases-design** [comment]
FYI - 
Enable Lightbox for product images is checked under Products > Display

**Comment by archetyped** [comment]
Hi, I would love to help. Please fill in the details of the issue you are having and I would be glad to take a closer look.

**Comment by phases-design** [comment]
It's pretty simply -- the lightbox is not working. 
I have current versions of WooCommerce, WordPress, Simple Lightbox, and Simple Lightbox Woocommerce plugins installed an enabled. 

Under admin > Woocommerce > Products > Display, I checked "enable lightbox for product image"

However, product images open the image as _blank, not in a lightbox. 

So basically, the plug in is not working.

**Comment by phases-design** [comment]
p.s. 
It's not the theme -- same issue with the default 2015 theme as with  my custom theme. 
It;s not a plug in conflict -- same issue happen with default them and ONLY woocommerce, simple lightbox, and simple lightbox woocommerce plugins enabled.

**Comment by archetyped** [comment]
Thank you for the additional information.  As requested in the **Details** section of the support ticket, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by phases-design** [comment]
It's a development site -- not launched yet. 
I have it blocked to logged in users only. I would be happy to provide you with a user account. Which email should I tie the account to?

**Comment by archetyped** [comment]
When you say "blocked", are you using HTTP authentication to restrict access to the site (e.g. via htaccess)?  If so, this can prevent SLB from accessing the resources it needs to function properly.

I would recommend temporarily removing the HTTP authentication to test SLB in a production setting.

**Comment by phases-design** [comment]
I  use a plug in "absolute privacy" 
I have deactivated it for you. FYI, it didn't resolve the issue....

http://dev.bitsibi.com/

**Comment by archetyped** [comment]
That URI does not appear to working.  Let me know when the site is up and I will take a closer look.

**Comment by archetyped** [comment]
The site is now loading and I was able to get a look at it.  The Woocommerce add-on is properly activating product images, but there are a few issues that are contributing to keeping SLB itself from functioning properly:

* Example URI: http://dev.bitsibi.com/shop/salted/
* Multiple versions of jQuery are being loaded on the page.  This can confuse scripts and the browser when jQuery is called.  [More information on jQuery support](https://github.com/archetyped/simple-lightbox/wiki/jQuery-Support).
* cURL disabled: It appears that the site does not have cURL enabled for local requests, which can prevent WordPress plugins (including SLB) from accessing the necessary resources to function properly.  [More information on SLB's minimum requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements)
* JavaScript error(s): e.g. `VK.init({apiId: , onlyWidgets: true});` (line 433).  JS errors can stop other scripts (such as SLB) from running.  Load your page with your browser's developer console to see these errors.

Resolving these issues on the site should allow SLB to function properly.

**Comment by phases-design** [comment]
Thank you! I'll look into each of them and post back if there are any issues after.

**Comment by phases-design** [comment]
Had the host enable cURL and everything working like a gem. Thank you!

**Comment by archetyped** [comment]
Glad to hear it :)
