### ISSUE TITLE
[Video Handler] Slightly oversized video near bottom of screen

### ISSUE THREAD

**Issue by m2008** [archetyped/slb-addons#33]
I installed video-add-on for SLB plugin on 2 wordpress sites with same CSS files and same plugins.  
One one site, the video add-on SLB plugin is working fine but on the other, the video display is slightly oversized and video appears near bottom of screen (see attached)
![slb](https://cloud.githubusercontent.com/assets/16084030/11474714/9461fa62-972e-11e5-96cb-18d63242b776.png) .  
The only difference in the 2 sites are one if http and the other https.  Could SSL be the cause of such an issue?

**Comment by archetyped** [comment]
Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by m2008** [comment]
Is there a non-public email or page I can send the link to?

**Comment by archetyped** [comment]
Hi, you can email support@archetyped.com.
