### ISSUE TITLE
[Video / Request]: Autoplay videos

### ISSUE THREAD

**Issue by tbrownvisuals** [archetyped/slb-addons#34]
## Description of feature/request
Video autoplay when lightbox opens

## This feature would be used to
Autoplay videos upon the lightbox appearing. Currently users have to click play. This would eliminate one click.

**Comment by archetyped** [comment]
Hi, autoplay is supported by adding the URI query parameter to the link's URI.

For example, a Vimeo or YouTube link with `&autoplay=1` added to the URI's query string will automatically start playing when it is displayed in the lightbox.

Full URI example:

```
https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
```

This gives you full control over which videos start playing automatically when loaded in the lightbox.
