### ISSUE TITLE
[Video] Question

### ISSUE THREAD

**Issue by davemeehan** [archetyped/slb-addons#35]
Not really an issue but I'm loading some vid links in using JS and I'm curious what code I should use to re-evaluate the page to attach your video player after dynamic links are added?

Thanks!

**Comment by archetyped** [comment]
Hi, SLB activates links on the server to improve accuracy and performance.  Links loaded via JS are not currently supported, but may be supported in the future via an [add-on](https://github.com/archetyped/simple-lightbox/issues/208).
