### ISSUE TITLE
[Video / Issue]: 

### ISSUE THREAD

**Issue by k9barry** [archetyped/slb-addons#36]
## Description of issue
Would like to request the ability to play .mp4 videos from the media gallery.  When they are played now they play without the lightbox.

## Details

* URL of page exhibiting the issue: http://mcta.us/alert/test-video
* Web Browser(s) that exhibit the issue: All
* Simple Lightbox Version: 2.5.2
* Active theme: 2016
* Other plugins installed: Yourchannel

**Comment by archetyped** [comment]
Hi, please add your comments to [the existing ticket for video file support](https://github.com/archetyped/slb-addons/issues/25).

Thanks.
