### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by EdwardN1** [archetyped/slb-addons#37]
Hello,

I have recently developed a site with both the main plugin and the video plugin working fine. We then installed an SSL and enforced SSL on the site by changing the Site URL. Now neither the video handler of the main plugin will work.

**Comment by archetyped** [comment]
Hi, the add-on is not affected by SSL, but the core plugin may be affected by the server's settings.  Please refer to the [existing ticket](https://github.com/archetyped/simple-lightbox/issues/112) for the core plugin for updates on this.

Thanks.
