### ISSUE TITLE
[Video / Request]: Size

### ISSUE THREAD

**Issue by AntonioGonzalo** [archetyped/slb-addons#39]
## Resizing the videos in the lightbox

I might be a little clumpsy, but I find nowhere to constrain the size of the youtube video to a comfortable size. It fills the whole screen, and it is really annoying to resize the window to make it watchable.

Is there anywhere in the code I can put '?width=800&height=600' ?

Thanks!

**Comment by archetyped** [comment]
Hi,

SLB displays videos at the size provided by the video service (e.g. YouTube, etc.), and they do not support setting dimensions via the URL.

As such, limiting the size of the lightbox to specific dimensions is not currently supported, but it may be possible via an add-on in the future.
