### ISSUE TITLE
[WooCommerce / Request]: 

### ISSUE THREAD

**Issue by matteoraggi** [archetyped/slb-addons#43]
## Description of feature/request

Lightbox clicking on the title of the prducts instead of images

## This feature would be used to

How to show the lightbox with photo and description when clicking on the title of the products?

**Comment by archetyped** [comment]
Hi, you can edit your theme's template to add an image link around the title text, and use `slb_activate()` to activate the link to be displayed in a lightbox.

See SLB's documentation for [more details on using `slb_activate()`](https://github.com/archetyped/simple-lightbox/wiki/Activation#manual-activation).
