### ISSUE TITLE
[WooSlider / Issue]: 

### ISSUE THREAD

**Issue by rdavey17** [archetyped/slb-addons#44]
## Description of issue
Hello, I am having an issue with Simple Lightbox conflicting with WooSlider. A gallery I created is only displaying the first two images in a lightbox and the others open the attachment in a new page. I submitted a ticket to WooSlider and they mentioned that it was a conflict with Simple Lightbox. Perhaps it is something I am just missing, but if you could help me out either way I would greatly appreciate it.

Thanks!

## Details

* URL of page exhibiting the issue: http://www.foxhillvillage.com/our-residences/remodels/
* Web Browser(s) that exhibit the issue: Chrome, Firefox, Edge
* Simple Lightbox Version: 2.5.3
* Active theme: Genesis
* Other plugins installed: 
Advanced Custom Fields Pro, Akismet, Black Studio TinyMCE Widget, Coming Soon Page & Maintenance Mode by SeedProd, Easy Table, Easy WP SMTP, Genesis Responsive Slider, Gravity Forms, iThemes Security, Shortcodes Ultimate, Testimonials, Velvet Blues Update URLs, WooSlider, WP Responsive Menu

**Comment by rdavey17** [comment]
Hello again, I just wanted to make sure that somebody noticed the issue I am having. I realize I sent this just before the holiday weekend so I understand that it has not been dealt with but I just wanted to make sure that somebody will be looking into it. 

Thanks again!

**Comment by archetyped** [comment]
Hi, there do not appear to be any image links on the page provided.  Please update the page or provide a link to a different page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by rdavey17** [comment]
Sorry, I had to remove the slider as the client was not happy with it in the state it was in but I reinstated it for now so you can check it out. Thank you for looking into this as well, I really appreciate it. http://www.foxhillvillage.com/our-residences/remodels/

**Comment by archetyped** [comment]
Thank you.  It appears that WooSlider only creates valid image links for the first two images on the server-side.  The rest of the slider's image links are rendered once the page is loaded in the browser.

SLB finds and activates valid links before the page's content is sent to the browser.  The slider's unrendered image links are unfortunately not accessible by SLB.

It may be possible to support WooSlider's behavior via an add-on.  I've added it to the list and will update this ticket if an add-on becomes available in the future.
