### ISSUE TITLE
[Video / Issue]: Lightbox not opening when link is in other plugin

### ISSUE THREAD

**Issue by gyzhor** [archetyped/slb-addons#45]
## Description of issue

Not sure this is an issue or a feature request, but I've installed the SLB Video add-on to my wordpress site, and it seems to work fine in ordinary href links, but when I add the link to an existing plugin (I'm trying to launch a video from a Meta Slider Pro slide) I'm taken to the youtube page.

Are there any work-around for this? I've added the link to the slider, to the text, and inserted it into the code, but with no affect.
## Details
- URL of page exhibiting the issue: unavailable (secured network}
- Web Browser(s) that exhibit the issue:  chrome (others untested)
- Simple Lightbox Version: 2.5.3
- Active theme: _underscores (custom)
- Other plugins installed: Meta Slider Pro

**Comment by archetyped** [comment]
Hi, how is the slider being added to the page?  SLB works with any valid link (including those generated by other plugins via shortcodes, etc.) in supported content areas such as page/post content, widgets, etc.

Links in content outside of these areas can be manually activated using `slb_activate()` ([see documentation for full details](https://github.com/archetyped/simple-lightbox/wiki/Activation#manual-activation)) and add-ons (such as the [WooCommerce add-on](http://archetyped.com/lab/slb-woocommerce-beta/)).

Extensions like the video add-on automatically work with activated links, whether they are activated automatically, manually, or via another add-on.

**Comment by gyzhor** [comment]
The plugin is deployed with shortcode in a page.
Looking at the page source a bit closer it looks like adding the link to the slider background gets it rendered out to a "datalink" property, which I wouldn't assume would work with SLB.
However, when I add an href directly to the slider code, or wrap the text of the slider in an href itself, it seems to render normally, but still doesn't activate SLB.

The site I'm working on is on a secure development server, so I can't show you exactly what I'm doing, but the live page (without SLB or youtube links in the slider) is here:
www.freezerworks.com

I'd appreciate any insights you might have!
Thanks,
~gyz

**Comment by archetyped** [comment]
Hi, as a paid plugin, I don't have access to Meta Slider Pro, but SLB was tested with the free version and it worked out of the box with all of the slider modules, save for Coin Slider (SLB activates the links properly, but this slider appears to block access to the actual links to perform its transitions).

For each slide, the desired image/video URL was set in the URL field.  When viewed in a post, Meta Slider appears to generate proper links which SLB activates for display in the lightbox.

If you are setting the desired image or video URL in each slide's URL field as described above and still experiencing issues, I would recommend testing the free version of Meta Slider to see if that works.

If the free version works, I would recommend contacting Meta Slider's developer to inquire about differences between the free and paid versions of the plugin.

If the free version also does not work for you, there may be an issue specific to your site.  I would be glad to take a closer look once you are able to provide a link to a page that exhibits the issue you are experiencing.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
