### ISSUE TITLE
[Video / Issue] Going straight to Vimeo link

### ISSUE THREAD

**Issue by zloveday** [archetyped/slb-addons#49]
This plugin is really inconsistent for me. 

Sometimes it pops up, sometimes it redirects to the Vimeo website. 

And now it seems to be redirecting to the Vimeo website every single time I click a Vimeo link. 

What is going on with this?

Is there an update I don't know about? I currently have Version 0.2.0 of Simple Lightbox:Video Handler and Version 2.5.3 of Simple Lightbox. 

This is really frustrating - and would like to sort it ASAP. 

Let me know what links you need from me - as all of this is done inside a private members area and don't want to give away a username and password publicly. 

-Zak

**Comment by archetyped** [comment]
Hi, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

You can email login details, etc. to support@archetyped.com

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
