### ISSUE TITLE
[Video / Issue]: Activate Anywhere

### ISSUE THREAD

**Issue by psasso** [archetyped/slb-addons#51]
## Description of issue

1.) Can't get SLB YouTube Video to activate from a menu item:
         http://lightupyourholidays.us/
      Click in 'Watch "Before & After"

### I've install this PHP:

```php
<?php $content = '<a href="https://www.youtube.com/watch?v=DC7OF9SSsWM"></a>';
if ( function_exists('slb_activate') )
    $content = slb_activate($content);
echo $content; ?>
```

2.)  Is there anyway I can make the video autoplay?

## Details

* URL of page exhibiting the issue: http://lightupyourholidays.us/
* Web Browser(s) that exhibit the issue: Chrome
* Simple Lightbox Version: 2.5.3
* Active theme: iFeature Pro (CyberChimps)
* Other plugins installed: Too Many to List! But none seem to conflict.

**Comment by psasso** [comment]
Sorry. The PHP snippet above got corrupted. It should read like this:

`<?PHP $content = '<a href="https://www.youtube.com/watch?v=DC7OF9SSsWM"></a>';
if ( function_exists('slb_activate') )
    $content = slb_activate($content);
echo $content; ?>`

**Comment by archetyped** [comment]
Hi, `slb_activate()` is a template tag, which means it is used in your theme's template files to manually activate links.  [Menu activation is planned](https://github.com/archetyped/simple-lightbox/issues/533), but in the meantime, you can save a menu's output to a variable by setting the menu's `echo` option to `false` and then passing it through `slb_activate()` as per your original example.

See [WordPress' documentation for full details on using `wp_nav_menu()` for more details](https://developer.wordpress.org/reference/functions/wp_nav_menu/).

### Autoplay

The video add-on fully supports [YouTube's video player parameters](https://developers.google.com/youtube/player_parameters), allowing you to customize the experience when the video is loaded in the lightbox. For example, by [using the autoplay parameter](https://developers.google.com/youtube/player_parameters#autoplay), videos should start playing automatically once loaded in the lightbox.

This information was also included in my reply to your previous  email, so you may want to check your spam folder if you did not receive that email.
