### ISSUE TITLE
[Video / Issue]: 

### ISSUE THREAD

**Issue by Luxe30** [archetyped/slb-addons#55]
## Description of issue
The video lightbox doesn't have the ability to close like the photo lightbox. I'd like to be able to click outside the box and get back to the page, or at least have an x in the corner.

## Details

* URL of page exhibiting the issue: https://www.luxe30.com/subscriptions-2/ (it's the last thumbnail under "classic")
* Web Browser(s) that exhibit the issue: Chrome
* Simple Lightbox Version: Version 2.6.0 (and video handler version Version 0.2.0)
* Active theme: Fashion Woocommerce
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, the link to the video is being opened directly, not in a lightbox.  [Support for MP4 files is planned](https://github.com/archetyped/slb-addons/issues/25), but as noted on [the Video add-on's page](https://archetyped.com/lab/slb-video-addon-beta/), links to YouTube and Vimeo videos are currently supported.
