### ISSUE TITLE
'slb_viewer_layout' div not vertically centered on mobile

### ISSUE THREAD

**Issue by DocWhitaker** [archetyped/slb-addons#56]
I've been having an issue with where the lightbox appears on the smaller, mobile sized screens. At a screen width of something like 497px or less SLB will start to generate at the very top of the screen. Sizes above 497px seem to work fine. I can't find the source of the problem myself and I'm pretty sure there aren't any crazy break-points on my website at 497px wide that would conflict with slb, so I'm a bit stumped.

[Here](http://psyskip.com) is my site. SLB is activated on the 'showreel' button.

Thanks

**Comment by archetyped** [comment]
Hi, SLB's default themes are designed to fill the view on small screens to make the most of the limited screen area. It looks like the lightbox is not extending to the bottom of the screen, so I am looking into that and will address it in a future update.

Thanks!
