### ISSUE TITLE
[WooCommerce / Feedback]: 

### ISSUE THREAD

**Issue by figure2** [archetyped/slb-addons#57]
## My Feedback

Greetings,

I have been looking for a lightbox which will work with woocommerce on both the main image and secondary product gallery. I am interested in trying your woocommerce addon but the download button on  <a href="https://archetyped.com/lab/slb-woocommerce-beta/?utm_source=internal&utm_medium=slb-add-ons&utm_campaign=woocommerce">that page</a> indicates the download link is for the video addon, not the woocommerce addon.

I assume this is an error. If I click that button will I get the woocommerce addon?

Mark Hannon
hannonart@gmail.com

**Comment by archetyped** [comment]
Hi, yes you will get the WooCommerce add-on.  I've corrected the typo, thank  you for pointing it out :)
