### ISSUE TITLE
[WooCommerce / Issue]: Error: Missing Argument

### ISSUE THREAD

**Issue by smooty1970** [archetyped/slb-addons#58]
## Description of issue
Warning:  Missing argument 4 for SLB_WooCommerce::activate_product_thumbnail() in /itbcs402/public_html/lochnershop.at/wp-content/plugins/slb-woocommerce_0.2.1/controller.php

## Details

* URL of page exhibiting the issue: https://www.lochnershop.at
* Web Browser(s) that exhibit the issue: IE11
* Simple Lightbox Version: 2.6.0
* Active theme: VendiProVersion: 1.4.2
* Other plugins installed: 
Check and Enable GZIP compression

Contact Form 7

Envato WordPress Toolkit

Google Analytics Dashboard für WP

Head, Footer and Post Injections

Image Widget
Deaktivieren | Bearbeiten

Imagify

ManageWP - Worker

Meta Slider

Really Simple CAPTCHA

Resize images before upload

Schema Creator by Raven

SEO Friendly Images

Simple Custom CSS

Simple Lightbox

Simple Lightbox: WooCommerce Activator

Vendidero Helper

Visser Labs Updater

W3 Total Cache

Woo Payment Discounts

WooCommerce

WooCommerce - Store Exporter

WooCommerce - Store Exporteur Deluxe

WooCommerce Colors

WooCommerce Deutsch (de_DE)

WooCommerce Germanized

WooCommerce Table Rate Shipping

WordPress HTTPS

WP CDN Rewrite

WP-Lister Pro for eBay

WPDBSpringClean

Yoast SEO

**Comment by archetyped** [comment]
Hi, what versions of WooCommerce and SLB are you using?  The current stable release for each plugin should be installed:

* WooCommerce: 2.6.14
* Simple Lightbox: 2.6.0

**Comment by smooty1970** [comment]
We use exactly these versions. When the SLB Addon is activated, the error appears. The theme is VendiPro in the current version.

**Comment by smooty1970** [comment]
In the line 107 of the controller.php, the error occurs:
	public function activate_product_thumbnail($output, $attachment_id, $post_id, $image_class) {

[03-Mar-2017 17:46:25 UTC] PHP Warning:  Missing argument 4 for SLB_WooCommerce::activate_product_thumbnail() in /home/itbcs402/public_html/lochnershop.at/wp-content/plugins/slb-woocommerce_0.2.1/controller.php on line 107

**Comment by archetyped** [comment]
Hi, it sounds like the theme may be overriding the function in a way that is not compatible with WooCommerce's default functionality.  I would recommend testing this by temporarily switching to a standard theme (such as Woo's [Storefront theme](https://woocommerce.com/storefront/) or one of WordPress' default built-in themes like [Twenty Seventeen](https://wordpress.org/themes/twentyseventeen/)).

If the error message goes away when a different theme is activated, then the theme is causing the error and I would recommend contacting the theme's developer to request that they update the theme to be compatible with WooCommerce.

Please let me know what you find and I would be glad to take another look if necessary.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
