### ISSUE TITLE
[Video / Issue]: Not lightboxing

### ISSUE THREAD

**Issue by ownboss** [archetyped/slb-addons#61]
## Details: I used a youtube link: https://www.youtube.com/embed/QSGDNiUtDiI?rel=0 and tried an iFrame code the video is active but not within a lightbox.

* URL of page exhibiting the issue: http://www.trends2000.net/mca/get-your-free-gift-and-watch-our-video/
* Web Browser(s) that exhibit the issue: Firefox 52.0.2
* Simple Lightbox Version: 2.6.0 and Video Handler 0.2.0
* Active theme: Lighthouse
* Other plugins installed: https://www.dropbox.com/s/kxi0kcvsu73wp8f/2017-04-15_17-21-57.png?dl=0

**Comment by archetyped** [comment]
Hi, a video's embed URL is intended for displaying a YouTube player widget directly on the page.  Use the video's standard URL (e.g. `https://www.youtube.com/watch?v=QSGDNiUtDiI`) in the link and you should be good to go.
