### ISSUE TITLE
Video handler not working in Divi theme

### ISSUE THREAD

**Issue by larrym31** [archetyped/slb-addons#62]
## Description of Problem

Simple Lightbox works beautifully but the Video Handler does not work. Videos continue to open in their own windows as if the plugin were not installed. 

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* WordPress: 4.7.5
* Theme/Version: Divi 3.0.49
* Version of SLB Installed: 
* Add-on/Version: Video Handler 0.2.0 (beta)
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, SLB and the Video handler have been tested with the Divi theme.  Please update your original post to include the information necessary to evaluate your specific issue.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
