### ISSUE TITLE
[Video / Issue]: Vimeo link not working

### ISSUE THREAD

**Issue by thecolab** [archetyped/slb-addons#63]
## Description of issue
Vimeo link not working, it just doesn't work I assumed it was supposed to work automatically.

## Details

* URL of page exhibiting the issue: reviewwave.wpengine.com
* Web Browser(s) that exhibit the issue: Firefox MacOS
* Simple Lightbox Version: Version 2.6.0 with purchased video handler
* Active theme: Genesis Showcase Pro
* Other plugins installed: 
- Don’t Muck My Markup
- Genesis Columns Advanced
- Genesis Extender
- Widget Content Blocks

**Comment by archetyped** [comment]
Hi, SLB does not appear to be activated at the link you provided.  Please let me know when SLB and the video add-on are activated on the site and I would be glad to take another look.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
