### ISSUE TITLE
[Video / Issue]: YouTube Autoplay not working

### ISSUE THREAD

**Issue by skolmarketing** [archetyped/slb-addons#64]
Please contact me at sbohler@bohlersolutions.com for this issue.  Thank you.

## Description of issue
Autoplay doesn't work on YouTube videos, or I don't know the proper way to enable it with slb-handler-video.  Please advise.

## Details
My YouTube URLs are structured as follows:
https://youtu.be/nnnnn**?autoplay=0&showinfo=0&controls=0&showinfo=0&modestbranding=1&rel=0**

* URL of page exhibiting the issue: https://cscoe-mn.org/careers-new/
* Web Browser(s) that exhibit the issue: Chrome
* Simple Lightbox Version: 2.6.0 with video handler v0.2.0
* Active theme: CSCOE
* Other plugins installed: Many.  Autoplay fails even with all plugins other that those required to test disabled.  Autoplay and other Youtube parameters do not get passed to the output video url.

**Comment by archetyped** [comment]
Hi, apologies for the delayed response.  Autoplay is supported, but the parameter's value needs to be `1` not `0` (e.g. `?autoplay=1`) for it to be enabled.

I would also recommend using the full `youtube.com` URL for the video as opposed to the `youtu.be` shortlink version, as YouTube's oEmbed API may not consistently support it.

Let me know if you are are still experiencing this issue after making the above changes and I would be glad to reopen this ticket at take another look.

Thanks.
