### ISSUE TITLE
[Video / Issue]: Can't install the Simple Lightbox Video Add on Plugin. 

### ISSUE THREAD

**Issue by crichw3** [archetyped/slb-addons#65]
## Description of issue

Can't install the Simple Lightbox Video Add on Plugin. 
Error Message is "The package could not be installed. No valid plugins were found. Plugin install failed."

## Details

* URL of page exhibiting the issue: www.veepstack.com
* Web Browser(s) that exhibit the issue: Chrome Version 60.0.3112.90
* Simple Lightbox Version: Version 2.6.0
* Active theme: Unicon
* Other plugins installed: Contact Form 7, Slider Revolution, Unicon Portfolio, WP Super Cache, WooCommerce, Yoast SEO, Visual Composer Clipboard, PDF Viewer, Duplicate Post, Content Protector, Easy Smooth Scroll Links.

**Comment by archetyped** [comment]
Hi, apologies for the delayed response.  Please let me know which step in the installation instructions that are included with the Video Add-on you are encountering an issue with and I would be glad to assist.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
