### ISSUE TITLE
Video not displaying on Simple Lightbox Video plugin

### ISSUE THREAD

**Issue by markpijones** [archetyped/slb-addons#66]
I just purchased the Video add on but the lightbox just displays a rotating wheel?

The test page is http://spiritdatacapture.com/video-test/ . 

The link code is <a href="https://youtu.be/_1ZWqKZ5dtQ">Video</a>

As you can see on this page the image lightbox works fine so maybe it is the video plugin?

Thanks for your help

**Comment by markpijones** [comment]
Actually it works now but is very slow, I thought the plugin didn't need to upload the full video but it seems to be doing this?

**Comment by archetyped** [comment]
Apologies for the delayed response, I was not getting notifications on new issues for some reason.

The Video add-on does not load the entire video when a link is clicked, but rather it fetches the video info (title, player embed code, etc.) from the vendor (e.g. YouTube, Vimeo, etc.) via a server-side request.  As such, the response time of your server and/or the vendor can affect how long it takes for the video to start playing in the lightbox.

In this particular case, it looks like your server is taking a longer than normal time to respond (5-7 seconds).  I've tested your video URLs on my own server and they loaded very quickly (~500ms), so I would recommend checking your server's logs and checking with your web-hosting company for any bottlenecks that may be affecting your server's response time.
