### ISSUE TITLE
[Video / Issue]: i cant belive i can not make it work xD

### ISSUE THREAD

**Issue by jijorod** [archetyped/slb-addons#68]
## Description of issue
Hello everyone :)

Forgive me for disturbing you, I'm only at the first step with the plugin but I block! I offered myself the video version to place vimeo videos on my site.

I can not link to a video vimeo.

Could you please help me to make a complete link with an autoplay?
for example one of my videos to install

https://vimeo.com/246308188

Thank you for your help.

I will have another request, is there an exhaustive list of options that can be used in the video link with vimeo and your plugin?

Thank you again for your help.
See you soon.

## Details

* URL of page exhibiting the issue: 
* Web Browser(s) that exhibit the issue: 
* Simple Lightbox Version: 
* Active theme: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, here is a tutorial inserting links in WordPress posts and pages: [How to Add a Link in WordPress](http://www.wpbeginner.com/beginners-guide/beginners-guide-on-how-to-add-a-link-in-wordpress/ "How to Add a Link in WordPress").

From there, all you need to do is link to the desired Vimeo video and Simple Lightbox will handle the rest!

Also, the video add-on supports [Vimeo's custom URL parameters](https://help.vimeo.com/hc/en-us/articles/115004485728-Autoplaying-and-looping-embedded-videos) for customizing the player.  For example, autoplaying the above Vimeo URL in the lightbox is as simple as using the following URL for your link:

`https://vimeo.com/246308188?autoplay=1`

If you're still experiencing an issue with getting things to work, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to reopen this ticket and take a closer look.
