### ISSUE TITLE
[Video / Issue]: Video not loading in lightbox

### ISSUE THREAD

**Issue by thetompi** [archetyped/slb-addons#70]
## Description of Problem

Hy!

My Product Page Contain the following string, but the video doesn't displayed in the Lightbox:

Link: <a href="https://www.youtube.com/watch?v=51aU8pMWjsU">https://www.youtube.com/watch?v=51aU8pMWjsU</a>

What's the problem?

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Version of Video Add-on installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
