### ISSUE TITLE
[Video / Issue]: Does not work as advertised!

### ISSUE THREAD

**Issue by James-Wallis62** [archetyped/slb-addons#71]
## Description of issue
I purchased the $8.00 Lightbox video plugin for WordPress. It does not work as advertised. The instructions that came with it are useless. I am a WP newbie but I can at least install a plugin and get it to work! If you can't provide simple instructions that will work then I demand a refund please. I'm trying to use it with "Video Grid with Lightbox". When that alone didn't work I purchased the $8.00 Lightbox Video plugin thinking that might fix it. It didn't. I'm pasting the YouTube video "share" link into the grid and that works fine except the video plays in YouTube. I want them to play in Lightbox. Can you help or refund my money please?

## Details

* URL of page exhibiting the issue: 
* Web Browser(s) that exhibit the issue: Google Chrome
* Simple Lightbox Version: 0.2.0
* Active theme: Malory
* Other plugins installed: Contact Form 7, Duplicator, Ebor Framework, Slider Revolution, Video Grid With Lightbox, WP Less, WPBakery Visual Composer, Yoast SEO

**Comment by archetyped** [comment]
Hi, as described on the [Video add-on's page](https://archetyped.com/lab/slb-video-addon-beta/), this is an add-on that extends the functionality of the [Simple Lightbox](https://wordpress.org/plugins/simple-lightbox/) plugin.  As such, installing Simple Lightbox must be installed an activated as well.

Once Simple Lightbox and the Video add-on are both activate, video links (including YouTube links) will be opened in a lightbox when clicked.

If you are still experiencing an issue once both of the above are activated, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

Thanks.

**Comment by James-Wallis62** [comment]
Thanks for clearing that up for me. It works fine now. One thing that took me a while to grasp is that you don't use the YouTube "Share" link. Rather, you copy the URL from the location bar in your browser. If the URL doesn't start with "https://www.youtube.com/watch..." then it won't work.

**Comment by archetyped** [comment]
Glad to hear the video add-on is working for you now.

The short URL provided by YouTube's Share functionality is definitely supported by the Video add-on. If you are experiencing an issue with this, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
