### ISSUE TITLE
[WooCommerce / Feedback]: WooCommerce 3.0 support

### ISSUE THREAD

**Issue by johnbotton** [archetyped/slb-addons#72]
## My Feedback

Hi, do you have a delivery date for compatibility with woo commerce 3.0?

Thanks
John

**Comment by archetyped** [comment]
Hi, support for WooCommerce v3+ is a top priority.  A lot has changed in v3.0 so particular attention is being paid to ensure everything functions properly.

**Comment by johnbotton** [comment]
Thanks for your response. Do you have any timeline for this?
