### ISSUE TITLE
[Video / Issue]:  Plugin Not Working, no light box functionality

### ISSUE THREAD

**Issue by Pocketsalmon** [archetyped/slb-addons#73]
## Description of issue
Doesn't work, not creating or using light boxes for youtube links.

## Details

* URL of page exhibiting the issue: 
https://galadefinancial.com/financial-planning/
* Web Browser(s) that exhibit the issue: 
Chrome
* Simple Lightbox Version: 
Version 2.7.1
Video: Version 0.2.0 
* Active theme: 
Experon Pro Child
* Other plugins installed: 
![image](https://user-images.githubusercontent.com/48102711/53590396-a785b380-3b5f-11e9-964d-198177aa8c92.png)

**Comment by archetyped** [comment]
Hi, I see an embedded YouTube video player, but no links to YouTube videos.  Without any links, there is nothing for visitors to click on to launch the lightbox.

See the **Demo** link on [the Video Add-on's page](https://archetyped.com/lab/slb-video-addon-beta/) for an example of a video link.

Please provide an updated link if you are still experiencing an issue with the video add-on after adding YouTube links to the page, and I would be glad to reopen this ticket and take another look.

Thanks.

**Comment by Pocketsalmon** [comment]
There is no ebbed player, just the youtube link

**Comment by Pocketsalmon** [comment]
![image](https://user-images.githubusercontent.com/48102711/53597044-2a623a80-3b6f-11e9-8242-2190475eeb30.png)

**Comment by archetyped** [comment]
Hi, that is not a link, but rather a bare URL. WordPress converts certain bare URLs into embedded content (i.e. an embedded player in the case of YouTube URLs). 

If you select this text (or any other text/image/etc.) in the editor, click the insert link button, and add a YouTube video URL as the link, then it will create a link on the page that will be displayed in the lightbox.
