### ISSUE TITLE
[Video / Issue]: Advanced Custom Fields & Simple lightbox Video Add-on 

### ISSUE THREAD

**Issue by shopowner58** [archetyped/slb-addons#75]
## Description of issue

Hi, I want to use the video lightbox on a portfolio page.
I am using ACF. my custom field is `<?php the_field( 'video_url' ); ?>`
This gives the following result: https://www.youtube.com/watch?v=XzTCntGgNJU
How can I implement the code in my single-portfolio.php file?

This is not working
`<p><a href="<?php the_field( 'video_url' ); ?>" data-slb-active="1" data-slb-asset="1" data-slb-group="1">open video</a></p>
`
Can you please tell me how to fix this issue?

## Details

* URL of page exhibiting the issue: 
* Web Browser(s) that exhibit the issue: 
* Simple Lightbox Version: latest
* Active theme: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, manually adding SLB-specific attributes to a link will generally not do anything as they are primarily meant for internal use.

You can manually activate a link with the `slb_activate()` template tag.  See [SLB's documentation on manual link activation ](https://github.com/archetyped/simple-lightbox/wiki/Activation#manual-activation) for more details and example code.
