### ISSUE TITLE
[Video / Request]: Videopress

### ISSUE THREAD

**Issue by amlozano9** [archetyped/slb-addons#76]
## Description of feature/request
Hi. Does this Add-on work with videos self-hosted with Videopress?

Thanks

## This feature would be used to
Allow Videopress videos to play in LightBox

**Comment by archetyped** [comment]
Hi, as per [the Video add-on's page](https://archetyped.com/lab/slb-video-addon-beta/), YouTube and Vimeo links are currently supported.

However, I've added VideoPress to the list of platforms to potentially support in a future update.

Thanks.
