### ISSUE TITLE
[WooCommerce / Issue]: Lightbox not working

### ISSUE THREAD

**Issue by junesvws** [archetyped/slb-addons#77]
## Description of issue
Hi, there. the Lightbox does not work. There is no change after activating the plugin. The pictures are on a subdomain. After I click on the Gallery pictures a new tab with the image opens. 
Thanks for help. Junes

## Details

* URL of page exhibiting the issue: https://jga-versand.de/produkt/junggesellinnenabschied/braut-blumenkranz/
* Web Browser(s) that exhibit the issue: Chrome
* Simple Lightbox Version: Version 2.7.1
* Active theme: Chaos Theme (http://preview.themeforest.net/item/chaos-responsive-bag-shop-theme/full_screen_preview/12067230)
* Other plugins installed: Redux Framework: von Team Redux – 3.6.15
WooCommerce Upsells Shortcode: von SkyVerge – 1.0.0 – Nicht getestest mit der aktiven WooCommerce-Version
Contact Form 7: von Takayuki Miyoshi – 5.1.4
Size Guide: von createIT – 1.4 – Nicht getestest mit der aktiven WooCommerce-Version
Individuelle Sidebars: von WPMU DEV – 3.2.3
Easy WP SMTP: von wpecommerce
alexanderfoxc – 1.3.9.1

Enhanced E-commerce for Woocommerce store: von Tatvic – 2.2.0
WooCommerce Show Single Variations by Iconic: von Iconic – 1.1.12
Imagify: von WP Media – 1.9.6
WPBakery Page Builder: von Michael M - WPBakery.com – 5.4.7
Mailchimp for WordPress: von ibericode – 4.5.3
N-Media WooCommerce PPOM PRO: von Najeeb Ahmad – 17.0 – Nicht getestest mit der aktiven WooCommerce-Version
Relevanssi: von Mikko Saari – 4.3.1.1
RoadThemes Helper: von RoadThemes – 1.0.0
SEO Friendly Images: von Vladimir Prelovac – 3.0.5
Shortcode Pagination for WooCommerce: von James Kemp – 1.0.10 – Nicht getestest mit der aktiven WooCommerce-Version
Shortcodes Ultimate: von Vladimir Anokhin – 5.3.0
Simple Lightbox: von Archetyped – 2.7.1
Simple Lightbox: WooCommerce Activator: von Archetyped – 0.2.1 – Nicht getestest mit der aktiven WooCommerce-Version
Trustami - Ein Siegel für alle Kundenbewertungen: von Trustami GmbH – 1.0.4 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Dynamic Pricing & Discounts: von RightPress – 2.3.1
Checkout Field Editor for WooCommerce: von ThemeHiGH – 1.3.5
WooCommerce Cart popup premium: von XootiX – 1.4 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Print Invoice & Delivery Note: von Tyche Softwares – 4.4.2
WooCommerce Amazon Pay Gateway: von WooCommerce – 1.9.1 – 1.10.2 ist verfügbar
WooCommerce Stripe-Gateway: von WooCommerce – 4.2.3
WooCommerce Germanized: von Vendidero – 2.0.4
WooCommerce Multiple Free Gift: von lilmonkee – 1.2.3 – Nicht getestest mit der aktiven WooCommerce-Version
N-Media WooCommerce PPOM: von Najeeb Ahmad – 17.3
WooCommerce Google Product Feed: von Lee Willis – 3.3 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce TM Extra Product Options: von themeComplete – 4.6.9.2
WooCommerce: von Automattic – 3.3.5 – 3.7.0 ist verfügbar
Yoast SEO: von Team Yoast – 11.0
WooCommerce Multi-Step Checkout: von SilkyPress – 2.3
WP Rocket: von WP Media – 3.3.6
WP Sitemap Page: von Tony Archambeau – 1.6.2
Yoast WooCommerce SEO: von Team Yoast – 1.1.5 – Nicht getestest mit der aktiven WooCommerce-Version
YITH Color and Label Variations for WooCommerce: von YITH – 1.8.11
YITH WooCommerce Compare: von YITH – 2.3.13
YITH WooCommerce Wunschliste: von YITH – 2.2.13

**Comment by archetyped** [comment]
Hi, it looks like you are using an unsupported version of WooCommerce.  As noted in the Requirements section on SLB's [WooCommerce add-on page](https://archetyped.com/lab/slb-woocommerce-beta/), the add-on currently supports up to WooCommerce v2.6.14.

WooCommerce introduced several breaking changes with v3+ updates, so development is currently underway to add compatibility for WooCommerce v3+.

Thanks.
