### ISSUE TITLE
[Video / Issue]: Youtube link attached to pic on page navigates to youtube not popping lightbox.

### ISSUE THREAD

**Issue by dcellsworth** [archetyped/slb-addons#78]
## Description of issue

Youtube link attached to pic on page navigates to youtube not popping lightbox.

## Details

* URL of page exhibiting the issue: https://cabinetplacewaukesha.com/
* Web Browser(s) that exhibit the issue: Firefox
* Simple Lightbox Version: Just installed yesterday after purchase (2.7.1, 0.2.0)
* Active theme: Oxygen Builder
* Other plugins installed: Defender lite, Schema & Structured Data for WP, Bluehost

**Comment by archetyped** [comment]
Hi, I do not see any YouTube links at the page you provided (only an unlinked thumbnail image).  Please update the page or provide an updated link that exhibits the issue you are experiencing and I would be glad to take another look.

Thanks.

**Comment by dcellsworth** [comment]
The client couldn’t wait for a solution that worked so I had to move to something else. Could you please refund my $8? 

Thanks, 

David

**Comment by archetyped** [comment]
Hi, please reply to the confirmation email you received for the add-on so that I can locate the original order.

Thanks.
