### ISSUE TITLE
[WooCommerce / Issue]: Cannot activate wooCommerce addon

### ISSUE THREAD

**Issue by matmartinstudio** [archetyped/slb-addons#80]
## Description of issue
I'm using the SLB addon for wooCommerce but not seeing the option to enable this in the wooCommerce settings as per the readme file in the download:

> When the lightbox is enabled in WooCommerce's settings, Simple Lightbox will display images in a lightbox.

The linked images are still simply opening in the bowser window and replacing the page. SLB is working fine in non-wooCommerce situations.

Where in the wooCommerce settings is this option located please?

## Details

* URL of page exhibiting the issue: Locally installed
* Web Browser(s) that exhibit the issue: Firefox, Chrome, Safari, Opera
* Simple Lightbox Version: 2.8.1 
* Active theme: Custom

**Comment by archetyped** [comment]
Closing (duplicate ticket).
